In [2]:
import pandas as pd
df = pd.read_csv("solicitudes_credito.csv", sep=";")

    
df = pd.read_csv("solicitudes_credito.csv", sep=";",encoding = 'utf-8')
df = pd.read_csv('solicitudes_credito.csv', sep=";",encoding = 'utf-8-sig')
df['fecha_de_beneficio'] = pd.to_datetime(df['fecha_de_beneficio'])

df

C:\Users\vanfa\AppData\Local\Temp\ipykernel_13712\3936473003.py:7: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  df['fecha_de_beneficio'] = pd.to_datetime(df['fecha_de_beneficio'])

,Unnamed: 0,sexo,tipo_de_emprendimiento,idea_negocio,barrio,estrato,comuna_ciudadano,fecha_de_beneficio,monto_del_credito,línea_credito
0,0,masculino,COMERCIO,charcuteria,manrique central no. 2,1,3.0,2017-12-28,7000000,microempresarial
1,1,masculino,comercio,distribuidora de,santa lucia,2,12.0,2018-03-16,"$ 7,000,000.00",microempresarial
2,2,masculino,comercio,tienda,belen,3,16.0,2018-02-14,7800000,microempresarial
3,3,masculino,servicio,organización y,robledo,2,7.0,2016-08-09,1500000,microempresarial
4,4,masculino,servicio,COMIDAS RAPIDAS,20 de julio,2,13.0,2016-12-20,3000000,microempresarial
...,...,...,...,...,...,...,...,...,...,...
10915,10915,femenino,industria,cafeteria,santo domingo savio,1,1.0,2018-06-22,1000000,microempresarial
10916,10916,femenino,comercio,variedades,villa del socorro,2,2.0,2019-01-04,7000000,microempresarial
10917,10917,femenino,comercio,comidas rapidas,la libertad,2,8.0,2018-05-22,7812000,microempresarial
10918,10918,femenino,comercio,almacen de ropa en,caribe,3,5.0,2019-02-27,8281000,microempresarial
10919,10919,femenino,servicio,fabrica de alimentos,andalucia,2,2.0,2017-08-06,30000000,empresarial ed.

In [3]:
df_mod = df.copy()
df_mod = df_mod.iloc[:,1:]
df_mod['fecha_de_beneficio'] = pd.to_datetime(df_mod['fecha_de_beneficio'],dayfirst=True)
df_mod.drop_duplicates(inplace = True)
df_mod.dropna(axis=0,inplace=True)

df_mod

,sexo,tipo_de_emprendimiento,idea_negocio,barrio,estrato,comuna_ciudadano,fecha_de_beneficio,monto_del_credito,línea_credito
0,masculino,COMERCIO,charcuteria,manrique central no. 2,1,3.0,2017-12-28,7000000,microempresarial
1,masculino,comercio,distribuidora de,santa lucia,2,12.0,2018-03-16,"$ 7,000,000.00",microempresarial
2,masculino,comercio,tienda,belen,3,16.0,2018-02-14,7800000,microempresarial
3,masculino,servicio,organización y,robledo,2,7.0,2016-08-09,1500000,microempresarial
4,masculino,servicio,COMIDAS RAPIDAS,20 de julio,2,13.0,2016-12-20,3000000,microempresarial
...,...,...,...,...,...,...,...,...,...
10913,femenino,comercio,almacen de ropa en,campo valdes no. 1,3,4.0,2018-04-07,2000000,microempresarial
10914,femenino,comercio,cafeteria,la america,3,12.0,2018-03-20,5000000,microempresarial
10915,femenino,industria,cafeteria,santo domingo savio,1,1.0,2018-06-22,1000000,microempresarial
10918,femenino,comercio,almacen de ropa en,caribe,3,5.0,2019-02-27,8281000,microempresarial
10919,femenino,servicio,fabrica de alimentos,andalucia,2,2.0,2017-08-06,30000000,empresarial ed.

In [5]:
 #transformacion columna sexo
df_mod['sexo'] = df_mod['sexo'].str.lower()

df_mod['sexo'].value_counts()

femenino     6783
masculino    3686
Name: sexo, dtype: int64

In [6]:
#transformacion columna tipo_emprendimiento
df_mod.tipo_de_emprendimiento.fillna('sin tipo',inplace = True)
df_mod['tipo_de_emprendimiento'] = df_mod['tipo_de_emprendimiento'].str.lower()

df_mod['tipo_de_emprendimiento'].value_counts()

comercio        5793
servicio        2259
industria       2247
agropecuaria     170
Name: tipo_de_emprendimiento, dtype: int64